### ISSUE TITLE
Saga module not working

### ISSUE THREAD

**Issue by Spartacus1** [lutraconsulting/qgis-mac-packager#52]
I've been testing processing modules because of the Grass issue and found out that several are not working either. As far as I tested, SAGA and GDAL processing modules are also not working in QGIS 3.5 and in 3.4.3. **Both are working fine in 3.4.2.**

Test with a simple points shape file:
  - Saga - Vector point tops - Add coordinates to points (will fail)
- GDAL - vector geopreocessing - Buffer vectors (will fail)

GDAL buffer above returns:

Processing algorithm…
Algorithm 'Buffer vectors' starting…
Input parameters:
{ 'DISSOLVE' : False, 'DISTANCE' : 1000, 'EXPLODE_COLLECTIONS' : False, 'FIELD' : None, 'GEOMETRY' : 'geometry', 'INPUT' : '/Users/xxxxxxxx/Desktop/Project_Porto/Layers/points_porto.shp', 'OPTIONS' : '', 'OUTPUT' : '/private/var/folders/r_/12_57str8xggjl001s75rfhr0000gn/T/processing_d86a66e3c2c84d3da52e27490ea1cb43/5ee6ed6b9ab04bc59f82aba74fef23ee/OUTPUT.shp' }

GDAL command:
ogr2ogr /private/var/folders/r_/12_57str8xggjl001s75rfhr0000gn/T/processing_d86a66e3c2c84d3da52e27490ea1cb43/5ee6ed6b9ab04bc59f82aba74fef23ee/OUTPUT.shp /Users/xxxxxxxx/Desktop/Project_Porto/Layers/points_porto.shp -dialect sqlite -sql "SELECT ST_Buffer(geometry, 1000.0) AS geometry,* FROM 'points_porto'" -f "ESRI Shapefile"
GDAL command output:
dyld: Symbol not found: _iconv

Referenced from: /usr/lib/libcups.2.dylib

Expected in: /Applications/QGIS3.4.3.app/Contents/MacOS/lib/libiconv.2.dylib

in /usr/lib/libcups.2.dylib

Execution completed in 0.16 seconds
Results:
{'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':/private/var/folders/r_/12_57str8xggjl001s75rfhr0000gn/T/processing_d86a66e3c2c84d3da52e27490ea1cb43/5ee6ed6b9ab04bc59f82aba74fef23ee/OUTPUT.shp, 'createOptions': {'fileEncoding': 'System'}}>}

Loading resulting layers
The following layers were not correctly generated.<ul><li>/private/var/folders/r_/12_57str8xggjl001s75rfhr0000gn/T/processing_d86a66e3c2c84d3da52e27490ea1cb43/5ee6ed6b9ab04bc59f82aba74fef23ee/OUTPUT.shp</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by Spartacus1** [comment]
Hi ujavalgandhi. Try to install the version available from qgis.org. Then use this tip from the readme text:

********************************
"QGIS 3 does not find external tools needed for Processing.  Some configuration options are missing.  A workaround is to use QGIS custom variables.  Open QGIS Preferences → System.

- Under the Environment section, turn on Use Custom Variables.
- Add (+) a variable
- Select Prepend from the Apply popup
- Enter PATH for the variable
- For the Value enter:
/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/GDAL.framework/Versions/2.3/Programs:
- Quit QGIS 3 and start it again

NOTE: this may need to be updated when upgrading from a previous version of QGIS."

***************************

Then use QGIS4.3.2 from lutraconsulting and see if it works. I'm guessing that this is the reason for the modules to be working in 4.3.2. They do not work in the most recent versions starting from QGIS3.4.3.

**Comment by Spartacus1** [comment]
Now QGIS 3.4.2 is not working too!!

**Comment by Spartacus1** [comment]
GDAL modules from processing failing and giving error like these ones:

GDAL command output:
dyld: Symbol not found: _iconv

Referenced from: /usr/lib/libmecab.1.0.0.dylib

Expected in: /Applications/QGIS3.5.app/Contents/MacOS/lib/libiconv.2.dylib

in /usr/lib/libmecab.1.0.0.dylib

**Comment by PeterPetrik** [comment]
@Spartacus1 thanks for doing this testing. Unfortunately I need to finish some other projects until FF of QGIS, but after that I should have some time to focus on fixing the bugs for QGIS 3.6 official release in February. Feel free to ping me (hangout?) on peter.petrik@lutraconsulting.co.uk

I probably know what is broken, /usr/lib/libiconv.2.dylib is system library, but the packager thinks it is part of homebrew's libraries.

**Comment by Spartacus1** [comment]
Great Peter. I'll be paying attention. 

"I probably know what is broken, /usr/lib/libiconv.2.dylib is system library, but the packager thinks it is part of homebrew's libraries."

Probably the problem occurs with more libraries similar to this one. I don't remember which ones but there are similar problems with some other libraries in the same path. Probably the cause is the same that you are advancing. 

Things seem to go just fine until the end of each module but, in the end, it fails to write results. 
I'll continue to test new versions as soon as they come out.

**Comment by PeterPetrik** [comment]
unable to replicate locally with https://www.dropbox.com/s/9mdwobzn6ru5arb/qgis_pr_final-3_4_4_20190213_064551.dmg?dl=0. @Spartacus1 can you recheck? thanks

**Comment by Spartacus1** [comment]
Hi Peter

This version hangs on startup. Tested from the terminal and gave me the following message:

"  Reason: Incompatible library version: QGIS requires version 5.212.0 or later, but QtWebKit provides version 4.9.0
Abort trap: 6"

Cheers

**Comment by PeterPetrik** [comment]
fixed the error with QtWebKit in #62 , try https://www.dropbox.com/s/26abu37gvtotfky/qgis_pr_final-3_4_4_20190214_041422.dmg?dl=0 ?

**Comment by saberraz** [comment]
For me, with the latest version (https://www.dropbox.com/s/26abu37gvtotfky/qgis_pr_final-3_4_4_20190214_041422.dmg?dl=0) GDAL algs work but none of SAGA algs working

**Comment by PeterPetrik** [comment]
For GDAL python modules see https://github.com/lutraconsulting/qgis-mac-packager/issues/60

**Comment by PeterPetrik** [comment]
@saberraz what error SAGA gives?

**Comment by saberraz** [comment]
It closes the window..so I can't see it (selected "keep the processing dialog open" but still closes it)

**Comment by saberraz** [comment]
![image](https://user-images.githubusercontent.com/2649047/52793373-80aa8600-3065-11e9-9cfb-c93796875ded.png)

**Comment by Spartacus1** [comment]
Same here. modules do not work or fail to finish.

**Comment by Spartacus1** [comment]
In the end something like this always appear in red:

"
Loading resulting layers
The following layers were not correctly generated.<ul><li>/private/var/folders/r_/12_57str8xggjl001s75rfhr0000gn/T/processing_410a496d70444937b9371d5643faeb4e/2ac1a63c437348ffa528b68070d19db5/OUTPUT.sdat</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm."

**Comment by PeterPetrik** [comment]
fixed in https://www.dropbox.com/s/r0b01sg2393d2ey/qgis_nightly_master_20190217_121012.dmg?dl=0

**Comment by PeterPetrik** [comment]
@saberraz @Spartacus1 can you please retest?

**Comment by saberraz** [comment]
Nice work....all working.

**Comment by Spartacus1** [comment]
Working now Peter!
Thank you so much

.

**Comment by kobben** [comment]
Butthe same problem popped up again in 3_6_0_20190222_124710...!

**Comment by kobben** [comment]
Now in 3.6 the problem is back again (at least for GDAL)
qgis_pr_final-3_6_0_20190222_124710.dmg 
macOS 10.14.4 (18E226)

Tried running GDAL Hillshade:
GDAL command:
gdaldem hillshade /var/folders/zy/jv8h0qxs5blgxh57bn2fk7q00000gp/T/N19W072.hgt /private/var/folders/zy/jv8h0qxs5blgxh57bn2fk7q00000gp/T/processing_03e328d8c11a4fa19d2ca0b9c753325b/6a36f1dd3d5f45b499bd6227b7154483/OUTPUT.tif -of GTiff -b 1 -z 1.0 -s 1.0 -az 315.0 -alt 45.0
GDAL command output:
dyld: Symbol not found: _iconv
Referenced from: /usr/lib/libcups.2.dylib
Expected in: /Applications/QGIS3.6.app/Contents/MacOS/lib/libiconv.2.dylib
in /usr/lib/libcups.2.dylib

both .2.dylib files are present....
